name: TuringHype
favicon: null
layout_spectrum: 0.50083
typography_spectrum: 0.65202
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-74670654-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.06677082041278481
  lightness: 0.0553096083458513
  saturation: 0.4762701822910458
  rhythmicContrast: 0.6655117359478027
purpose: []
